package com.bridgelabzlinkedlist;

public class LinkedListMain {
    public static void main(String[] args) {

        LinkedList<Integer> linkedList1 = new LinkedList<>();
        linkedList1.push(70);
        linkedList1.push(30);
        linkedList1.push(56);
        System.out.println("---------------------");
        LinkedList<Integer> linkedList2 = new LinkedList<>();
        linkedList2.add(56);
        linkedList2.add(30);
        linkedList2.add(70);
        linkedList1.show();
        linkedList2.show();
        System.out.println("---------------------");
        LinkedList<Integer> linkedList3 = new LinkedList<>();
        linkedList3.add(56);
        linkedList3.add(30);
        linkedList3.add(45);
        linkedList3.add(70);
        linkedList3.show();
        System.out.println("---------------------");
        System.out.println("Deletion operation");
        linkedList3.show();
        linkedList3.deleteFirstElement(56);
        System.out.println("After deletion of 1st element");
        linkedList3.show();
        System.out.println("---------------------");
        LinkedList<Integer> linkedList4 = new LinkedList<>();
        linkedList4.add(56);
        linkedList4.add(44);
        linkedList4.add(30);
        linkedList4.add(45);
        linkedList4.add(70);
        linkedList4.show();
        System.out.println("Deletion operation");
        linkedList4.show();
        linkedList4.deleteLastElement(70);
        System.out.println("After deletion of 2nd element");
        linkedList4.show();
        System.out.println("---------------------");
        LinkedList<Integer> linkedList5 = new LinkedList<>();
        linkedList5.add(56);
        linkedList5.add(30);
        linkedList5.add(45);
        linkedList5.add(70);
        linkedList5.show();
        linkedList5.search(45);
        System.out.println("---------------------");
        LinkedList<Integer> linkedList6 = new LinkedList<>();
        linkedList6.add(56);
        linkedList6.add(30);
        linkedList6.add(45);
        linkedList6.add(70);
        System.out.println("**Before insert**");
        linkedList6.show();
        System.out.println(" ");
        System.out.println("**After insert**");
        linkedList6.insertAnyWhere(55,60);
        linkedList6.show();
        LinkedList<Integer> linkedList7 = new LinkedList<>();
        linkedList7.add(56);
        linkedList7.add(30);
        linkedList7.add(45);
        linkedList7.add(70);
        linkedList7.show();
        linkedList7.deleteAnElement(45);
        System.out.println("-------------");
        linkedList7.getSize();
        System.out.println("--------------");
        SortedLinkedList<Integer> sortingLinkedList=new SortedLinkedList<>();
        sortingLinkedList.add(15);
        sortingLinkedList.add(26);
        sortingLinkedList.add(5);
        sortingLinkedList.add(35);
        sortingLinkedList.add(4);
        System.out.println("before sort \n");
        sortingLinkedList.show();
        System.out.println("\n");
        System.out.println(" after sort ");
        sortingLinkedList.sort();
        sortingLinkedList.show();
    }
}
